version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command:
            #echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install --user -r requirements.txt
      - run:
          name: RUN UNIT TESTS
          command: coverage run -m --source=. pytest test/test_hello_world.py

      - run:
          name: GET CODE COVERAGE
          command: coverage report -m
workflows:
  build_test:
    jobs:
      - run_tests
      
